CMS_HOST: studio.openelephant.com
CMS_OAUTH2_SECRET: gCPG3UyCct3zICRzazdrB5fS
CONTACT_EMAIL: contact@example.com
DISCOVERY_MYSQL_PASSWORD: YiXGMUKu
DISCOVERY_OAUTH2_SECRET: PjZuQfle
DISCOVERY_OAUTH2_SECRET_SSO: sCj1BP1u
DISCOVERY_SECRET_KEY: Gb7oxJPGzNX1QzPYzhPw
ENABLE_HTTPS: true
ID: K0JQxkwVku5rQ4O4TleuI8Fg
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEowIBAAKCAQEAvyl0MFi+vkqNDlsktTBgoqLhcqXJB5fkSV+f8pwKdRS3DoXp

  a2KpTMG3l8xQKg3s4XaA2S2K/EFsof924eRAvixvpP9k+VPnGXLYNoZdIbM6tfRC

  2i7e7JO47gC544ncxsITLWj0lg/i1Tv4hVUJZlRf5ONtqCxvSaUCu/sXzty0hH+9

  mp3wb0hhwCzXePWIJbjgnRLhro1G3kRjPtnw4SBXruJ8NzQJSIhS/0KMYD7q7zAT

  ZvUWYgf5Qk6DCdG8FhAu2DjyO/U+rTIcElPQo+8Zu5d0IqtFgwVEDTHiNVJ9H7lk

  3719I5ChsH20Vsorhrvey+6qPEU6CxZ3YzgeoQIDAQABAoIBABeRFT1mm3FbQIOO

  EfrycV9rhC69qIhynda73ryqpxFjEeRM9wdhnOyVDzy8F//vQo5TLTRZDILnz+wy

  0eWsXZz0XnkxcTHZuapmAajLLM0cSvcmm11JnPr+hTR2S3R1SQ4J3BJjl4+uerD+

  GTfa0XNXoJDXxuuOOtQR70HchUVfsnWtw7w9E1n7X/VbbijPZjERJvfR1rcsN9My

  NA2RLnITUr4oXC7Km2t/Dv3m8qE/izGR+GaYQyWStJf3OCu0wNudQsrsCidZs9+C

  BwOGTLOl390e07YMardEXKYtRMErf0viAM5M5+Zrz7O67XpckTvM7nSkl8BzDBJR

  +8S+dh8CgYEAyzdo1vxBZNjrOX4SqS9xmh5omS9lJDDDgT3xiirYMtrYE5ZON+T9

  K7z3LslnLVVuHIRJytKSCChaAr+M0vnjyhBsrBWnbqEyzc/YHQ5IdVeIHtvpqnyo

  KR0CAYFpQ4hOswR0tT1byg/eVh/xMQLByRI6n3uyN8g3PFdUP+8Nmk8CgYEA8NB/

  FZNrl8S6WFlQrb+y81IwxF0hGsmxJxeqLhzKwJlG5Llw+YYKwMWVRtftowAp+Fln

  dvbwOJPkTDKhfcfAztL0X8opjYJ2Ku3Mnc3eY2VJ3Gidrl8c1LR+jKgEieBiXuNJ

  evrW/dPgPBXL7JfKOy+BWaAk/NIqdZ5msPmRrA8CgYAucyffnCFGb960cYDKczHA

  TJsUCKVRtGO7svD25/wrA6LIN18Bn7HOwY6ufxK6ZgCZPBOx7Je8jZylbCtAPiY3

  FbIBU6HFw8rdCFkZqx4c1Dkk9JdghMXbP+opde8dpJZ4jNgwZSoJ8b6caQi0bzDk

  SOplcdy2q2kUvdFgG8A8OQKBgQCDjcL/LGvIm0YZYaF7aY/+8NWHUED3e1t1ua3U

  RxJUKOfbp5qaFanmKYolC2zccQh8jYrCKKCOp+w93CLwraEc2414jt4oWi7nwMTZ

  KE/nCLxS1ivdyEPdx0Si3l6sW5IhuBS6RDIStB55dIbUlw95SbhmF+Bc5Qsg+gmr

  gIsd7QKBgF+b9285P+Xh5xyVCVzMl5h960/bXaKYoEgXsLdJD1U7jxmRx4IPUl+q

  8kKQmhmcDpRznYNQ4xRZ6PQT/ibEMRVx/M5Dg3gocoG9uYD7h+DphJqX8a2SsEmq

  +D0xJcG2pSYOJlf+dpvnkX5k0yfUKs/nh76ZkM0WI6vBlRIB4KW7

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: openelephant.com
MOUNTS:
- /home/ubuntu/edx-platform
MYSQL_ROOT_PASSWORD: uicgnjpc
OPENEDX_MYSQL_PASSWORD: oSO1hp0E
OPENEDX_SECRET_KEY: v4rDen3yNpHEmmp1p0aVvZ6y
PLATFORM_NAME: OpenElephant
PLUGINS:
- custom_plugins
- forum
- mfe
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
